name: school_wall_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: 3.0.10
  json_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  build_verify: ^1.0.0
  json_serializable: ^3.2.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/tabbar/home.png
    - assets/images/tabbar/home_active.png
    - assets/images/tabbar/subject.png
    - assets/images/tabbar/subject_active.png
    - assets/images/tabbar/group.png
    - assets/images/tabbar/group_active.png
    - assets/images/tabbar/mall.png
    - assets/images/tabbar/mall_active.png
    - assets/images/tabbar/profile.png
    - assets/images/tabbar/profile_active.png
    - assets/images/home/wish.png