name: school_wall_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: 3.0.10

  cookie_jar: ^1.0.0 # 最新版本获取：https://github.com/flutterchina/cookie_jar
  dio_cookie_manager: ^1.0.0 # 最新版本获取：https://github.com/flutterchina/dio/tree/master/plugins/cookie_manager

  path_provider: ^1.6.27 # 最新版本：https://pub.dev/packages/path_provider
  json_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  build_verify: ^1.0.0
  json_serializable: ^3.2.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/tabbar/home.png
    - assets/images/tabbar/home-active.png
    - assets/images/tabbar/myself.png
    - assets/images/tabbar/myself-active.png
    - assets/images/tabbar/publish.png
    - assets/images/tabbar/publish-active.png
    - assets/images/home/anonymity.png